[workspace]
authors = ["sudoer_wsl_r9950x <wsl_r9950x@sudoer.cn>"]
channels = ["conda-forge"]
name = "Agent"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
openai = ">=2.26.0,<3"
